# Idle time to automatically lock screen
TIMEOUT_LOCK_MINUTES=5

# After this lock delay, allow any user to logout the current session by pressing ESC key
TIMEOUT_DELOG_MINUTES=21

# After this lock delay, the current session will be automatically logged out
TIMEOUT_DELOG_FORCED_MINUTES=47