#!/usr/bin/env bash

if [[ -v __HOME__ ]];then
    return
else
    __HOME__=true
fi

home_clean () {
    if [ -f "$HOME/.reset" ]; then
		echo "Resetting home directory: $HOME"
		rm -rf "$HOME/"
	elif [ -d $HOME ]; then
		echo "Cleaning cache"
		find $HOME/ -maxdepth 1 -type d -name .cache -exec rm -rf '{}' + || true
		find $HOME/.config/ -name 'Singleton*' -delete || true
	fi
}
